### PR TITLE
Om139

### PR DESCRIPTION
**Pull request by mphanias**
7.0 changes - initial changes to support multi-cluster view

### CODE REVIEW

**Review by hev — CHANGES_REQUESTED** [review]
There are still scenarios where a warning results in a red hex. We should filter the namespace and node panels to critical instead of the variable and remove the variable.  

Cursor_and_Multi_Cluster_View_-7p_-_Dashboards_-_Grafana

**Comment by mphanias** [comment]
modified alert query to consider only "critical" severity while showing color in Node (Hex) and Namespace panels

**Comment by mphanias** [comment]
removed alert- severity filter variable also, as it is no more required

**Review by hev — CHANGES_REQUESTED** [review]
I think version 794194738457c2f16f0036cfafec9846eb5cf9a4 was better. If we can only choose two colors it should be red (with hardcoded critical filter) or green for no critical.

**Comment by mphanias** [comment]
keeping only RED colour, however using only "critical", mean some key alerts which are marked as warn / error (example XDRTimelag a warn alert) will not show any indication, may leave user with assumption of all-is-good. 
I am thinking of these options, 1. use critical/warn or 2. look at all warn alerts and adjust the severity as critical or appropriate

**Review by hev — APPROVED** [review]
OK with this version.

**Pull request merged**
