### PR TITLE
OM127 - 7.0 node view changes

### PR DESCRIPTION
**Pull request by mphanias**
initial checkin with all 7.0 changes
7.0 based theme to combine 6.0 and 7.0 changes while showing state, topk and time-series values

### CODE REVIEW

**Comment by hev** [comment]
Reviewed this across a split cluster. Planning some more testing, but some initial notes:

* Having clear version is really helpful for supporting upgrade

Node_Overview_7_-_Dashboards_-_Grafana


Alerting feedback
View_panel_-_Node_Overview_-_Aerospike_-_Dashboards_-_Grafana
* I'd expect this to be a sum of number of alerts on the node
* I don't think we should include warnings in this view. Just Critical IMO

Best Practice Check
Node_Overview_7_-_Dashboards_-_Grafana_and_Multi_Cluster_View_-_Aerospike_-_Dashboards_-_Grafana
* Should be yellow to match warnings color on alerts view
* Ideally best practice checks would describe the specific best practice. Or we can add instructions to run the command `asadm show best-practice`
* It may make sense to have an orange box for errors level alerts here also. 

* Finally I believe it is more correct to use Record Count instead of Object count.

**Review by hev — CHANGES_REQUESTED** [review]
See previous comment.

**Comment by hev** [comment]
One more comment. 

I wonder about offering a namepsace variable on this dashboard. Strictly speaking it seems like we should only filter on node for this dashbaord (I think its fine to keep it just wanted to note it here).

**Comment by mphanias** [comment]
1. changed the alerts panel as a pie chart - with this we can show all alerts in relevant colour
2. alerts panel is modded to show sum of all alerts
3. best-practice and node-up panels now represent same colour as warn & critical like alerts
4. added "asadm show best-practice" in the best-practice description
5. namespace filter not-changed as we felt as it would be helpful
6. "master objects" panel title is left as-is instead of records as metric name is master_objects

**Review by hev — APPROVED** [review]
Color changes look good.

**Pull request merged**
